### ISSUE TITLE
FR language support

### ISSUE THREAD

**Issue by ramram1048** [ramram1048/kagami#7]
Please contribute on [lang.json](https://github.com/ramram1048/kagami/blob/master/resources/lang.json).

**Comment by Ashalaya** [comment]
Hey hello, I forked your kagami project to add the French translation but I don't know how I could test it localy before asking for a PR.
Will it be quicker for you to test it on your side ? If that so I'll just PR the few changes that I made to the lang.js ;)

**Comment by ramram1048** [comment]
Hey @Ashalaya, thanks for your kind contribute!😀
i made new branch for test FR language you contributed, https://github.com/ramram1048/kagami/tree/dev-french.
you can test your works on new branch. try 
```npm start```
to start development server and set your ACT overlay URL onto `http://localhost:8080/`.

![act setting](https://user-images.githubusercontent.com/48747221/95017375-f2e53980-0693-11eb-9b98-a5f69bc515d0.png)

and i fixed some typo on your contribute, please check it out: https://github.com/ramram1048/kagami/commit/3b6224bc81a0ec3226a08270a1e91eab41e9b36f

try it out, and if you have any other questions or problem, write comment here or contact me on discord by `ram#5923`.

**Comment by Ashalaya** [comment]
Oh great ! A new branch thanks ^^ I'll try that tonight
